# ML-10 — Content Action Playbook

[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/kiran162005/flyrank-ml/blob/main/work/notebooks/w07_action_playbook.ipynb)

This skeleton is yours to fill. Work the sections **in order** — each one has a one-line hint. Simple words, honest numbers.

> Working with an AI assistant? Tell it to read `skills/README.md` first and load the one skill this assignment names on its card.

## 1. Ranked actions + reason codes

*The queue: what to do first, and why, in words a human trusts.*

## 1. Ranked actions + reason codes

The playbook ranks webpages by their observed search-performance opportunity so that a content team can review the highest-priority pages first. The ranking is a **decision-support queue**, not an automatic instruction to change content.

### Action priority

**1. REVIEW — highest priority**

Pages receive `REVIEW` when they have meaningful search exposure and a relatively low observed CTR. These pages may have a potential content or search-snippet opportunity, so they should be reviewed first by the SEO/content team.

**Reason code: `LOW_CTR_HIGH_VOLUME`**

The page has high observed impression volume and CTR below the baseline threshold. The combination is prioritized because a potential improvement on a high-exposure page could have greater practical value.

**2. WATCH — medium priority**

Pages receive `WATCH` when they have meaningful search exposure but do not meet the low-CTR condition. These pages remain useful candidates for monitoring but do not have as strong an observed signal for immediate review.

**Reason code: `HIGH_SEARCH_VOLUME`**

The page has meaningful observed search volume, but the available signals do not provide enough evidence for immediate refresh review.

**3. NO_ACTION — lowest priority**

Pages receive `NO_ACTION` when they do not meet the baseline search-volume threshold or do not show a strong enough observed signal to enter the review queue.

**Reason code: `LOW_PRIORITY`**

The available March 2026 signals do not indicate a sufficiently strong opportunity for prioritization.

### How a human should use the queue

The queue should be read from highest score to lowest score. A `REVIEW` recommendation means **“look at this page first,”** not **“refresh this page automatically.”** A reviewer should consider search intent, page quality, SERP context, seasonality, recent changes, and business relevance before deciding whether any content action is appropriate.

The reason code is deliberately simple so that a reviewer can understand why a page entered the queue without treating the score as proof of a required refresh.

## 2. Intended use and limits

*Who uses this, for what — and where it stops being valid.*

## 2. Intended use and limits

### Intended use

The Content Action Playbook is intended for **SEO and content teams** to prioritize webpages for manual review.

It can be used to:

* identify pages with relatively high search exposure and low observed CTR;
* organize a review queue using consistent reason codes;
* focus limited content-review resources on potentially higher-value opportunities;
* provide a transparent starting point for deciding whether a page needs investigation, monitoring, or no immediate action.

The output is **decision support**. A `REVIEW` recommendation means that a page should be investigated by a human; it does not mean that the page definitely requires a content refresh.

### Limits

The playbook is based on observed search-performance signals and should not be interpreted as causal evidence that changing a page will improve rankings, CTR, or traffic.

It is not designed to:

* predict Google ranking changes;
* guarantee future traffic or CTR improvement;
* automatically decide that content is outdated;
* replace SEO or editorial judgment;
* recommend automatic content edits, deletion, or publication;
* generalize beyond the data period and validation setup without further testing.

Low CTR can have several explanations, including search intent, query mix, SERP features, ranking position, seasonality, or external changes. Therefore, every high-priority page requires human investigation before an action is taken.

The queue should also be revalidated when the underlying data period, feature definitions, target definition, or operating environment changes substantially.

## 3. Human review + the no-go list

*What a person must check before acting. What should never be automated.*

## 3. Human review + the no-go list

Every `REVIEW` recommendation must be checked by a human before any content action is taken. The model identifies a potential opportunity; the reviewer decides whether the opportunity is real and what action, if any, is appropriate.

### Human review checklist

Before acting on a recommended page, the reviewer should check:

1. **Search intent** — Does the page satisfy the intent behind the queries generating its impressions?
2. **Ranking context** — Is the low CTR reasonably explained by ranking position or SERP features?
3. **Content quality** — Is the information accurate, useful, complete, and appropriately structured?
4. **Freshness** — Is there evidence that the information is outdated or needs updating?
5. **Query mix** — Are impressions coming from relevant queries, or from unexpected/low-value queries?
6. **Recent changes** — Has the page, title, content, URL, or search environment changed recently?
7. **Business relevance** — Is improving this page valuable for the site's goals?
8. **Expected value vs. effort** — Is the potential benefit large enough to justify the time and resources required?

The reviewer should record the final decision, such as **refresh, monitor, investigate further, or no action**, rather than treating the model recommendation as the final decision.

### No-go list: actions that should NOT be automated

The system must not automatically:

* rewrite or publish webpage content;
* change titles, meta descriptions, URLs, or internal links;
* delete, redirect, or merge pages;
* declare content “outdated” solely from the model score;
* guarantee that a refresh will increase traffic, rankings, or CTR;
* make changes based only on low CTR without checking search intent and ranking context;
* override editorial, SEO, legal, or business review;
* use the queue as evidence of a causal relationship between a content change and future performance.

**Operating principle:** the model ranks pages for human attention; humans remain responsible for deciding and executing content changes.

## 4. Monitoring / retrain triggers

*What would tell you the recommendations went stale?*

## 4. Monitoring / retrain triggers

The action queue should be monitored periodically to detect when its recommendations no longer represent the underlying search environment. Monitoring is intended to identify when the current rules or model should be reviewed or retrained, rather than automatically changing the system.

### Monitoring signals

The following signals should be checked:

* **Feature drift:** impressions, clicks, CTR, ranking position, or other input distributions change substantially from the development/validation period.
* **Recommendation drift:** the proportion of pages receiving `REVIEW`, `WATCH`, and `NO_ACTION` changes substantially.
* **Outcome quality:** pages prioritized for review no longer show the expected relationship between the recommendation and subsequent performance.
* **Data availability:** GSC/GA4 coverage or data completeness changes enough to affect the reliability of the input features.
* **Business or search-environment changes:** major SERP, traffic, seasonal, product, or site changes make the existing thresholds less representative.

### Retrain / recalibration triggers

A model or scoring rule should be reviewed or retrained when:

1. input distributions show sustained drift;
2. recommendation quality declines across multiple evaluation periods;
3. the underlying feature or target definition changes;
4. a new sufficiently representative validation period becomes available;
5. major changes in search behavior or the operating environment make the existing scoring logic unreliable.

Retraining should **not** be triggered by a single unusual page or short-term fluctuation. Changes should be confirmed over an appropriate monitoring period before updating the system.

### Operational principle

The playbook should be periodically re-evaluated using fresh, temporally separated data. If the ranking signal, data coverage, or observed usefulness of recommendations deteriorates, pause reliance on the existing queue and reassess the scoring logic before deploying an updated version.

## 5. Exports for the paper

*Write the queue (and any figures you want to reuse) to work/outputs/ — your paper builds on these files.*

## 5. Exports for the paper

The final ranked action queue and supporting figures are saved under `work/outputs/` and `work/figures/` so that the same artifacts can be reused consistently in the final paper.

The ranked queue contains the page identifiers, observed performance signals, action priority, score, and reason code. The queue is an analysis artifact for the paper and is kept out of Git because it contains client/content-level output.

Metrics and summary JSON files may be committed when they are required to document the final evaluation.

### Paper artifacts

* **Ranked action queue:** `work/outputs/action_playbook_queue.csv`
* **Supporting figures:** `work/figures/`
* **Metrics / summary JSON:** `work/outputs/`

The exported files should be generated from the final notebook run so that the paper uses exactly the same outputs as the validated analysis.

In [18]:
from huggingface_hub import login

login()

In [19]:
import os

print("HF_TOKEN exists:", bool(os.environ.get("HF_TOKEN")))

HF_TOKEN exists: False

In [20]:
from huggingface_hub import whoami

try:
    info = whoami()
    print("Hugging Face authentication: OK")
    print("User:", info.get("name") or info.get("fullname"))
except Exception as e:
    print("Hugging Face authentication: FAILED")
    print(type(e).__name__, str(e))

Hugging Face authentication: OK
User: Kiran1612

In [21]:
from huggingface_hub import get_token

hf_token = get_token()

print("HF token available:", hf_token is not None)

HF token available: True

In [22]:
import duckdb
import pandas as pd

con = duckdb.connect()

con.sql(f"""
    CREATE OR REPLACE SECRET hf_secret (
        TYPE HUGGINGFACE,
        TOKEN '{hf_token}'
    )
""")

baseline_df = con.sql("""
    SELECT
        client_hash_id,
        content_hash_id,
        SUM(gsc_impressions) AS impressions,
        SUM(gsc_clicks) AS clicks,
        CASE
            WHEN SUM(gsc_impressions) > 0
            THEN SUM(gsc_clicks) * 1.0 / SUM(gsc_impressions)
            ELSE 0
        END AS ctr,
        AVG(gsc_avg_position) AS avg_position
    FROM read_parquet(
        'hf://datasets/FlyRank/internship-warehouse/fact_content_daily_performance/month=2026-03/*.parquet',
        hive_partitioning=true
    )
    WHERE gsc_data_available IS TRUE
    GROUP BY client_hash_id, content_hash_id
    HAVING SUM(gsc_impressions) > 0
""").df()

print("Shape:", baseline_df.shape)
display(baseline_df.head())

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Shape: (176738, 6)

,client_hash_id,content_hash_id,impressions,clicks,ctr,avg_position
0,client_73cda7b4e4f265ea,content_b7e512995f79d5a6,1140.0,2.0,0.001754,4.394234
1,client_73cda7b4e4f265ea,content_05597932fe4da067,57.0,0.0,0.000000,2.714744
2,client_73cda7b4e4f265ea,content_905aa32a0230694e,149.0,0.0,0.000000,6.481453
3,client_73cda7b4e4f265ea,content_05434271b257bb68,1421.0,6.0,0.004222,6.320337
4,client_73cda7b4e4f265ea,content_d056587ff7faca0c,2770.0,16.0,0.005776,4.459107

In [23]:
# ML-10: Build and export the final action queue

from pathlib import Path

# Start from the actual March 2026 baseline data
ranked_actions = baseline_df.copy()

# ML-07 baseline rules
high_volume = ranked_actions["impressions"] >= 100
low_ctr = ranked_actions["ctr"] < 0.02

# Score
ranked_actions["score"] = 0
ranked_actions.loc[high_volume, "score"] = 1
ranked_actions.loc[high_volume & low_ctr, "score"] = 2

# Reason codes
ranked_actions["reason_code"] = "LOW_PRIORITY"
ranked_actions.loc[high_volume, "reason_code"] = "HIGH_SEARCH_VOLUME"
ranked_actions.loc[
    high_volume & low_ctr,
    "reason_code"
] = "LOW_CTR_HIGH_VOLUME"

# Actions
ranked_actions["action"] = "NO_ACTION"
ranked_actions.loc[high_volume, "action"] = "WATCH"
ranked_actions.loc[
    high_volume & low_ctr,
    "action"
] = "REVIEW"

# Rank the queue
ranked_actions = ranked_actions.sort_values(
    ["score", "impressions"],
    ascending=[False, False]
).reset_index(drop=True)

ranked_actions.insert(0, "rank", range(1, len(ranked_actions) + 1))

# Create output directories
Path("work/outputs").mkdir(parents=True, exist_ok=True)
Path("work/figures").mkdir(parents=True, exist_ok=True)

# Export
queue_path = Path("work/outputs/action_playbook_queue.csv")
ranked_actions.to_csv(queue_path, index=False)

print("ML-10 EXPORT: PASS")
print(f"Queue saved to: {queue_path}")
print(f"Rows: {len(ranked_actions):,}")

print("\nAction distribution:")
print(ranked_actions["action"].value_counts())

print("\nReason-code distribution:")
print(ranked_actions["reason_code"].value_counts())

print("\nTop 10 ranked pages:")
display(ranked_actions.head(10))

ML-10 EXPORT: PASS
Queue saved to: work/outputs/action_playbook_queue.csv
Rows: 176,738

Action distribution:
action
REVIEW       100660
NO_ACTION     75297
WATCH           781
Name: count, dtype: int64

Reason-code distribution:
reason_code
LOW_CTR_HIGH_VOLUME    100660
LOW_PRIORITY            75297
HIGH_SEARCH_VOLUME        781
Name: count, dtype: int64

Top 10 ranked pages:

,rank,client_hash_id,content_hash_id,impressions,clicks,ctr,avg_position,score,reason_code,action
0,1,client_e547b89c05043229,content_eadb33b5df496f4a,617124.0,5668.0,0.009185,2.383011,2,LOW_CTR_HIGH_VOLUME,REVIEW
1,2,client_e547b89c05043229,content_ec2e0346994fb5a5,245276.0,1480.0,0.006034,2.854514,2,LOW_CTR_HIGH_VOLUME,REVIEW
2,3,client_23a62021009f63c4,content_e8a52cf3d5988c07,244931.0,669.0,0.002731,15.008339,2,LOW_CTR_HIGH_VOLUME,REVIEW
3,4,client_e547b89c05043229,content_0e03de7680314cd5,221310.0,720.0,0.003253,2.675217,2,LOW_CTR_HIGH_VOLUME,REVIEW
4,5,client_23a62021009f63c4,content_44f34c0a90047651,212404.0,24.0,0.000113,7.346909,2,LOW_CTR_HIGH_VOLUME,REVIEW
5,6,client_62f4a7e64f5e0096,content_7172a7fad43f0998,205867.0,862.0,0.004187,3.367835,2,LOW_CTR_HIGH_VOLUME,REVIEW
6,7,client_08a6a72ff48e62c0,content_e7b5dd4dff461ad2,205045.0,2446.0,0.011929,4.544203,2,LOW_CTR_HIGH_VOLUME,REVIEW
7,8,client_e547b89c05043229,content_8d7d99f109e19aa2,203497.0,289.0,0.001420,2.563756,2,LOW_CTR_HIGH_VOLUME,REVIEW
8,9,client_62f4a7e64f5e0096,content_f107e54b10b43725,195997.0,996.0,0.005082,3.186054,2,LOW_CTR_HIGH_VOLUME,REVIEW
9,10,client_23a62021009f63c4,content_36e53e9c707674fc,194579.0,242.0,0.001244,32.766674,2,LOW_CTR_HIGH_VOLUME,REVIEW

In [24]:
import pandas as pd

check = pd.read_csv("work/outputs/action_playbook_queue.csv")

print("EXPORT CHECK: PASS")
print("Shape:", check.shape)

print("\nAction counts:")
print(check["action"].value_counts(dropna=False))

print("\nReason-code counts:")
print(check["reason_code"].value_counts(dropna=False))

display(check.head(10))

EXPORT CHECK: PASS
Shape: (176738, 10)

Action counts:
action
REVIEW       100660
NO_ACTION     75297
WATCH           781
Name: count, dtype: int64

Reason-code counts:
reason_code
LOW_CTR_HIGH_VOLUME    100660
LOW_PRIORITY            75297
HIGH_SEARCH_VOLUME        781
Name: count, dtype: int64

,rank,client_hash_id,content_hash_id,impressions,clicks,ctr,avg_position,score,reason_code,action
0,1,client_e547b89c05043229,content_eadb33b5df496f4a,617124.0,5668.0,0.009185,2.383011,2,LOW_CTR_HIGH_VOLUME,REVIEW
1,2,client_e547b89c05043229,content_ec2e0346994fb5a5,245276.0,1480.0,0.006034,2.854514,2,LOW_CTR_HIGH_VOLUME,REVIEW
2,3,client_23a62021009f63c4,content_e8a52cf3d5988c07,244931.0,669.0,0.002731,15.008339,2,LOW_CTR_HIGH_VOLUME,REVIEW
3,4,client_e547b89c05043229,content_0e03de7680314cd5,221310.0,720.0,0.003253,2.675217,2,LOW_CTR_HIGH_VOLUME,REVIEW
4,5,client_23a62021009f63c4,content_44f34c0a90047651,212404.0,24.0,0.000113,7.346909,2,LOW_CTR_HIGH_VOLUME,REVIEW
5,6,client_62f4a7e64f5e0096,content_7172a7fad43f0998,205867.0,862.0,0.004187,3.367835,2,LOW_CTR_HIGH_VOLUME,REVIEW
6,7,client_08a6a72ff48e62c0,content_e7b5dd4dff461ad2,205045.0,2446.0,0.011929,4.544203,2,LOW_CTR_HIGH_VOLUME,REVIEW
7,8,client_e547b89c05043229,content_8d7d99f109e19aa2,203497.0,289.0,0.001420,2.563756,2,LOW_CTR_HIGH_VOLUME,REVIEW
8,9,client_62f4a7e64f5e0096,content_f107e54b10b43725,195997.0,996.0,0.005082,3.186054,2,LOW_CTR_HIGH_VOLUME,REVIEW
9,10,client_23a62021009f63c4,content_36e53e9c707674fc,194579.0,242.0,0.001244,32.766674,2,LOW_CTR_HIGH_VOLUME,REVIEW

## Self-check

Before you submit, confirm each line honestly:

- [ ] Every section above is filled — markdown thinking AND the code that backs it
- [ ] The notebook runs top to bottom with no errors (Runtime → Run all)
- [ ] No client names, URLs, or private queries anywhere
- [ ] My claims use careful words: observed, measured, directional, decision-support
- [ ] Committed to my repo under `work/notebooks/` — then submit your repo URL on the card. Done.